const express = require('express');
const router = express.Router();
const CouponController = require('../../../controllers/CouponController');

/**
 * /admin
 * @url http://localhost:5001/admin/coupon
 *
 */

router.get('/', CouponController.getAllCoupons);
router.get('/overview', CouponController.getCouponsOverview);
router.get('/coupon-details', CouponController.getCouponById);
router.get('/auto-generate', CouponController.getAutoGeneratedCoupon);
router.post('/add', CouponController.addCoupon);
router.post('/update', CouponController.updateCoupon);
router.post('/delete', CouponController.deleteCoupon);

module.exports = router;
